### ISSUE TITLE
The code for learning a linear function

### ISSUE THREAD

**Issue by songqsh** [songqsh/MQP2019#15]
- Improve
[this](https://nbviewer.jupyter.org/github/songqsh/MQP2019/blob/master/other/linearfunction01.ipynb).

- Perfect, see 
[this](https://github.com/songqsh/MQP2019/blob/master/Nick/Copy_of_linearfunction01.ipynb)
But, it needs rigorous but friendly mathematical description.

**Comment by nickwotton** [comment]
Proposition to close this issue?

**Comment by songqsh** [comment]
Good job
