### ISSUE TITLE
Why is CRR arbitrage free?

### ISSUE THREAD

**Issue by songqsh** [songqsh/MQP2019#21]
refer 
[this](https://github.com/songqsh/MQP2019/blob/master/doc/prj_crr.pdf)

**Comment by vitaltavares** [comment]
Hello professor, should we relate this to the probabilities of an asset going up/down and the risk-free rate?

**Comment by songqsh** [comment]
Dear Vital
I will detail out the question later. Yes, it relates to asset price and
rate.
Best

**Comment by songqsh** [comment]
Please see 
https://github.com/songqsh/MQP2019/blob/master/other/bin_tree.ipynb
